#
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: fileshare
  licenses: Apache-2.0
apiVersion: v2
appVersion: v0.0.5
dependencies:
  - name: common
    repository: "file://../../../common/charts/common"
    version: 2.31.1
description: file sharing and collaboration platform
home: https://minbzk.github.io/mijn-bureau-infra/
keywords:
  - fileshare
maintainers:
  - name: mijn-bureau-infra
    url: "https://minbzk.github.io/mijn-bureau/"
name: conversations
sources:
  - https://github.com/suitenumerique/conversations
version: 0.1.0
