{{- /*

SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.backend.themeCustomization.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "docs.theme.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  default.json: |
    {{ .Values.backend.themeCustomization.fileContent | toJson | indent 4 }}
{{- end }}
